INSERT INTO tbl_book (title, pubId) values('Together Again',1);
INSERT INTO tbl_book (title, pubId) values('Out Cold',5);
INSERT INTO tbl_book (title, pubId) values('First Knight',2);
INSERT INTO tbl_book (title, pubId) values('Hercules',6);
INSERT INTO tbl_book (title, pubId) values('God Bless America',1);
INSERT INTO tbl_book (title, pubId) value('Blue State',1);
INSERT INTO tbl_book (title, pubId) values('Pronto',4);
INSERT INTO tbl_book (title, pubId) values('Beauty in Trouble (Kráska v nesnázích)',6);
INSERT INTO tbl_book (title, pubId) values('Colt 38 Special Squad',1);
INSERT INTO tbl_book (title, pubId) values('Simple Wish, A',14);
INSERT INTO tbl_book (title, pubId) values('Cannonball Run II',6);
INSERT INTO tbl_book (title, pubId) values('The Green Years',12);
INSERT INTO tbl_book (title, pubId) values('Hunchback of Notre Dame',2);
INSERT INTO tbl_book (title, pubId) values('Four Heads Are Better Than One',3);
INSERT INTO tbl_book (title, pubId) values('Hey, Hey, It\'s Esther Blueburger',4);
INSERT INTO tbl_book (title, pubId) values('Master of the House',6);
INSERT INTO tbl_book (title, pubId) values('Cars That Ate Paris, The',5);
INSERT INTO tbl_book (title, pubId) values('World of Kanako, The (Kawaki.)',1);
INSERT INTO tbl_book (title, pubId) values('Cry_Wolf (a.k.a. Cry Wolf)',12);
INSERT INTO tbl_book (title, pubId) values('Me, Myself & Irene',15);
INSERT INTO tbl_book (title, pubId) values('Loving Story, The',1);
INSERT INTO tbl_book (title, pubId) values('Aria',17);
INSERT INTO tbl_book (title, pubId) values('Barrier (Bariera)',3);
INSERT INTO tbl_book (title, pubId) values('Young Winston',20);
INSERT INTO tbl_book (title, pubId) values('TiMER',19);
INSERT INTO tbl_book (title, pubId) values('Beautiful Losers',18);
INSERT INTO tbl_book (title, pubId) values('Women, The',10);
INSERT INTO tbl_book (title, pubId) values('Union: The Business Behind Getting High, The',13);
INSERT INTO tbl_book (title, pubId) values('Asylum Blackout',12);