INSERT INTO tbl_genre (genre_name) values('Art');
INSERT INTO tbl_genre (genre_name) values('Biography');
INSERT INTO tbl_genre (genre_name) values('Children');
INSERT INTO tbl_genre (genre_name) values('Comics');
INSERT INTO tbl_genre (genre_name) values('Classics');
INSERT INTO tbl_genre (genre_name) values('Christian');
INSERT INTO tbl_genre (genre_name) values('CookBooks');
INSERT INTO tbl_genre (genre_name) values('Fantasy');
INSERT INTO tbl_genre (genre_name) values('Poetry');
INSERT INTO tbl_genre (genre_name) values('Science Fiction');
INSERT INTO tbl_genre (genre_name) values('Romance');
INSERT INTO tbl_genre (genre_name) values('Sports');
INSERT INTO tbl_genre (genre_name) values('Graphic Novels');
INSERT INTO tbl_genre (genre_name) values('Music');
INSERT INTO tbl_genre (genre_name) values('Nonfiction');
INSERT INTO tbl_genre (genre_name) values('Mystery');
INSERT INTO tbl_genre (genre_name) values('Music');
INSERT INTO tbl_genre (genre_name) values('Horror');
INSERT INTO tbl_genre (genre_name) values('History');
INSERT INTO tbl_genre (genre_name) values('Psychology');
