INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Mann','14 Spenser Parkway','287-733-7380');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Upton-Gleason','5 Vera Point','173-957-3985');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Medhurst','3440 Dryden Street','945-122-1433');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Koelpin','3 Dapin Crossing','346-651-8550');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Waelchi Inc','100 Oxford Plaza','173-102-3837');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Upton LLC','768 Golf View Street','985-853-0625');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Simonis-Stiedemann','0227 Lawn Trail','378-510-6458');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Ziemann','63 Boyd Avenue','104-465-6125');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Konopelski-Bins','7340 Elgar Drive','251-773-6833');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Considine-Heidenreich','3 Jenna Lane','578-439-0120');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Stehr and Sons','7 Clemons Center','604-186-2314');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Rutherford-Smith','4 Erie Parkway','771-542-5665');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Kihn-Brakus','81262 Gale Junction','617-374-2951');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Leffler','72173 Wayridge Court','278-520-6387');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Klein','1 Colorado Alley','645-124-5020');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Kohler','2 5th Pass','366-318-0335');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Farrell','9591 Prairieview Park','466-492-8265');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Lueilwitz-Watsica','56680 Roxbury Street','883-328-1258');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Langworth and Sons','29398 Esker Park','296-515-2460');
INSERT INTO tbl_publisher (publisherName, publisherAddress, publisherPhone) values('Reichert','7589 Paget Street','463-825-8331');